version: "3.9"

services:
  flutter-runner:
    build: .
    container_name: flutter-runner
    environment:
      RUNNER_TOKEN: APW4GFHNUVNAEUWDJUC6STDJJFCWS      # short-lived token from GitHub
      REPO_URL: https://github.com/Appointment-Reminder
      RUNNER_NAME: Flutter-FrontEnd-Runner      # optional
      RUNNER_LABELS: flutter,docker,linux  # optional
    volumes:
      - flutter-runner-data:/home/runner/_work   # persist runner registration and _work
    restart: always

volumes:
  flutter-runner-data: