// Mocks generated by Mockito 5.4.6 from annotations
// in photography_business_frontend/test/features/user_create/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:photography_business_frontend/core/network/network_info.dart'
    as _i8;
import 'package:photography_business_frontend/features/user_create/data/datasources/auth_local_dataSource.dart'
    as _i7;
import 'package:photography_business_frontend/features/user_create/data/datasources/auth_remote_dataSource.dart'
    as _i5;
import 'package:photography_business_frontend/features/user_create/domain/entities/auth_result.dart'
    as _i3;
import 'package:photography_business_frontend/features/user_create/domain/entities/user.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_2 extends _i1.SmartFake implements _i4.User {
  _FakeUser_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i5.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i6.Future<_i3.AuthResult> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> register(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(
                this,
                Invocation.method(#register, [name, email, password]),
              ),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i4.User> validateToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#validateToken, [token]),
            returnValue: _i6.Future<_i4.User>.value(
              _FakeUser_2(this, Invocation.method(#validateToken, [token])),
            ),
          )
          as _i6.Future<_i4.User>);
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i7.AuthLocalDatasource {
  MockAuthLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.AuthResult> Login() =>
      (super.noSuchMethod(
            Invocation.method(#Login, []),
            returnValue: _i6.Future<_i3.AuthResult>.value(
              _FakeAuthResult_1(this, Invocation.method(#Login, [])),
            ),
          )
          as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> cacheUserLogin(_i3.AuthResult? authResult) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserLogin, [authResult]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult?> getCachedUserLogin() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedUserLogin, []),
            returnValue: _i6.Future<_i3.AuthResult?>.value(),
          )
          as _i6.Future<_i3.AuthResult?>);

  @override
  _i6.Future<void> Logout() =>
      (super.noSuchMethod(
            Invocation.method(#Logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
