name: Flutter CI

on:
  push:
    branches: [ "main", "dev", "staging" ]
  pull_request:
    branches: [ "main", "dev", "staging" ]

jobs:
  flutter-test:
    runs-on: [self-hosted, FlutterFrontEnd]
    steps:
      - uses: actions/checkout@v4

      - name: Set Flutter channel
        run: |
          flutter channel stable
          flutter upgrade
          flutter doctor -v

      - name: Navigate to project
        run: cd flutter_app

      - name: Get dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --coverage