name: Flutter CI

on:
  push:
    branches: [ "main", "dev", "staging" ]
  pull_request:
    branches: [ "main", "dev", "staging" ]

jobs:
  flutter-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run Flutter tests
        run: flutter test --coverage